import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const successConfettiConfig: ComponentConfig = {
  componentName: "SuccessConfetti",
  importPath: "@/components/remocn/success-confetti",
  controls: {
    count: {
      type: "number",
      default: 60,
      min: 10,
      max: 200,
      step: 5,
      label: "Particle count",
    },
    originX: {
      type: "number",
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.05,
      label: "Origin X",
    },
    originY: {
      type: "number",
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.05,
      label: "Origin Y",
    },
    gravity: {
      type: "number",
      default: 0.4,
      min: 0,
      max: 2,
      step: 0.05,
      label: "Gravity",
    },
    velocity: {
      type: "number",
      default: 12,
      min: 1,
      max: 40,
      step: 0.5,
      label: "Velocity",
    },
    text: { type: "text", default: "Merged!", label: "Text" },
    textColor: { type: "color", default: "#171717", label: "Text color" },
    background: { type: "color", default: "#fafafa", label: "Background" },
    seed: { type: "text", default: "remocn", label: "Seed" },
  },
  durationInFrames: 120,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
};
